import { snapshotQueryRequestSchema, type SnapshotQueryRequest, SNAPSHOT_QUERY_VERSION } from "./contracts.ts";
import { closeDuckDb, duckDbPath, openDuckDb } from "./duckdb.ts";
import { ingestSnapshot, snapshotReadiness } from "./ingest.ts";

const ALLOWED_QUERY_NAMES = new Set(["market_context_by_cbsa", "zip_cbsa_coverage", "regional_demand_by_zip_year", "regional_demand_by_cbsa_year", "clinic_profile_by_market", "clinic_activity_by_market", "cbsa_population_by_cbsa", "zip_context_by_zip", "zip_metro_by_zip", "clinic_market_evidence", "appointment_context", "retention_context", "google_ads_matched_location_context", "google_ads_market_aggregates", "source_quality_summary"]);

export function rejectArbitrarySql(sql: unknown): never { throw new Error(typeof sql === "string" && sql.trim() ? "Arbitrary SQL is not supported by the evidence boundary." : "A typed query name is required."); }

export async function querySnapshot(input: SnapshotQueryRequest, options: { databasePath?: string; snapshotDir?: string } = {}) {
  const parsed = snapshotQueryRequestSchema.parse(input);
  if (!ALLOWED_QUERY_NAMES.has(parsed.query)) return rejectArbitrarySql(parsed.query);
  const readiness = await snapshotReadiness(options);
  if (!readiness.manifestValid || readiness.snapshotVersion !== parsed.snapshotVersion) throw new Error("The requested snapshot version is unavailable or blocked.");
  if (["regional_demand", "clinic_market_summary", "clinic_performance_market_summary"].some((table) => readiness.restrictedDatasetsExcluded.includes(table)) && ["regional_demand_by_zip_year", "regional_demand_by_cbsa_year", "clinic_market_evidence"].includes(parsed.query)) {
    throw new Error("This evidence is confidential or restricted for browser and AI output and is blocked at the query boundary.");
  }
  try { await ingestSnapshot(options); } catch (error) { throw new Error(`Snapshot ingestion failed: ${error instanceof Error ? error.message : "unknown error"}`); }
  const handle = await openDuckDb(options.databasePath ?? duckDbPath(), true);
  const { connection } = handle;
  let sql = ""; let values: (string | number | null)[] = [];
  switch (parsed.query) {
    case "market_context_by_cbsa": sql = "SELECT marketId, cbsaCode, cbsaName, reportingDate, activeCustomerCount, activeCustomerYoyGrowth, totalHouseholds, qualityStatus, source.sourceId AS sourceId FROM market_context WHERE cbsaCode = ? LIMIT 100"; values = [parsed.cbsaCode]; break;
    case "zip_cbsa_coverage": sql = "SELECT zip, cbsaName, statisticalAreaType, source.sourceId AS sourceId FROM zip_market WHERE (? IS NULL OR zip = ?) LIMIT 1000"; values = [parsed.zip ?? null, parsed.zip ?? null]; break;
    case "regional_demand_by_zip_year": sql = "SELECT zip, year, netSalesExcludingRefunds, netSales, source.sourceId AS sourceId FROM regional_demand WHERE (? IS NULL OR zip = ?) AND (? IS NULL OR year = ?) LIMIT 5000"; values = [parsed.zip ?? null, parsed.zip ?? null, parsed.year ?? null, parsed.year ?? null]; break;
    case "regional_demand_by_cbsa_year": sql = "SELECT z.cbsaName, d.year, SUM(d.netSalesExcludingRefunds) AS netSalesExcludingRefunds, SUM(d.netSales) AS netSales, COUNT(*) AS contributingZipYearRows, 'regional-demand-by-cbsa-v1' AS calculationVersion FROM regional_demand d JOIN zip_market z ON d.zip = z.zip WHERE z.cbsaName = ? AND (? IS NULL OR d.year = ?) GROUP BY z.cbsaName, d.year ORDER BY d.year"; values = [parsed.cbsaName, parsed.year ?? null, parsed.year ?? null]; break;
    case "clinic_profile_by_market": sql = "SELECT CBSA_NAME AS cbsaName, COUNT(*) AS profileRows, COUNT(DISTINCT CLINIC_ID) AS clinicIds, SUM(TRY_CAST(TOTAL_ORDERS AS BIGINT)) AS totalOrders, SUM(TRY_CAST(TOTAL_VETS_CAPPED AS DOUBLE)) AS totalVetsCapped, SUM(CASE WHEN UPPER(CORPORATE_CLINIC_FLAG) = 'TRUE' THEN 1 ELSE 0 END) AS corporateClinicRows, SUM(CASE WHEN UPPER(PH_CLINIC_FLAG) = 'TRUE' THEN 1 ELSE 0 END) AS practiceHubRows, SUM(CASE WHEN UPPER(PBC_CLINIC_FLAG) = 'TRUE' THEN 1 ELSE 0 END) AS pharmacyBusinessRows, 'SNOWFLAKE-CSV-CLINIC-PROFILE' AS sourceId, 'clinic-profile-by-market-v1' AS calculationVersion FROM source_clinic_profile_raw WHERE (? IS NULL OR CBSA_NAME = ?) GROUP BY CBSA_NAME ORDER BY CBSA_NAME LIMIT 1000"; values = [parsed.cbsaName ?? null, parsed.cbsaName ?? null]; break;
    case "clinic_activity_by_market": sql = "SELECT z.CBSA_TITLE AS cbsaName, a.TIMEFRAME AS timeframe, COUNT(*) AS activityRows, COUNT(DISTINCT a.CLINIC_ID) AS clinicIds, SUM(TRY_CAST(a.TOTAL_CUSTOMER AS BIGINT)) AS totalCustomers, SUM(TRY_CAST(a.TOTAL_ORDERS AS BIGINT)) AS totalOrders, SUM(TRY_CAST(a.RX_ORDERS AS BIGINT)) AS rxOrders, SUM(TRY_CAST(a.NET_SALES AS DOUBLE)) AS netSales, SUM(TRY_CAST(a.RX_NET_SALES AS DOUBLE)) AS rxNetSales, SUM(TRY_CAST(a.NET_SALES_CHANGE AS DOUBLE)) AS netSalesChange, 'SNOWFLAKE-CSV-CLINIC-ACTIVITY' AS sourceId, 'clinic-activity-by-market-v1' AS calculationVersion FROM source_clinic_activity_raw a LEFT JOIN source_zip_market_raw z ON LPAD(REGEXP_REPLACE(a.ZIP_CODE, '[^0-9]', '', 'g'), 5, '0') = LPAD(REGEXP_REPLACE(z.ZIP_CODE, '[^0-9]', '', 'g'), 5, '0') WHERE (? IS NULL OR z.CBSA_TITLE = ?) AND (? IS NULL OR a.TIMEFRAME = ?) GROUP BY z.CBSA_TITLE, a.TIMEFRAME ORDER BY z.CBSA_TITLE, a.TIMEFRAME LIMIT 2000"; values = [parsed.cbsaName ?? null, parsed.cbsaName ?? null, parsed.timeframe ?? null, parsed.timeframe ?? null]; break;
    case "cbsa_population_by_cbsa": sql = "SELECT CBSA AS cbsaCode, LSAD AS statisticalAreaType, TRY_CAST(POP_ESTIMATE AS BIGINT) AS populationEstimate, 'SNOWFLAKE-CSV-CBSA-POPULATION' AS sourceId FROM source_cbsa_population_raw WHERE (? IS NULL OR LPAD(REGEXP_REPLACE(CBSA, '[^0-9]', '', 'g'), 5, '0') = ?) LIMIT 1000"; values = [parsed.cbsaCode ?? null, parsed.cbsaCode ?? null]; break;
    case "zip_context_by_zip": sql = "SELECT LPAD(REGEXP_REPLACE(GEO_ZIPCODE, '[^0-9]', '', 'g'), 5, '0') AS zip, TRY_CAST(ESTIMATED_HOUSEHOLDS AS BIGINT) AS households, TRY_CAST(ESTIMATED_MEDIAN_HOUSEHOLD_INCOME AS DOUBLE) AS medianHouseholdIncome, TRY_CAST(ESTIMATED_NUMBER_OF_FAMILIES AS BIGINT) AS families, 'SNOWFLAKE-CSV-ZIP-CONTEXT' AS sourceId FROM source_zip_context_raw WHERE (? IS NULL OR LPAD(REGEXP_REPLACE(GEO_ZIPCODE, '[^0-9]', '', 'g'), 5, '0') = ?) LIMIT 1000"; values = [parsed.zip ?? null, parsed.zip ?? null]; break;
    case "zip_metro_by_zip": sql = "SELECT LPAD(REGEXP_REPLACE(CUSTOMER_ADDRESS_ZIP, '[^0-9]', '', 'g'), 5, '0') AS zip, METRO AS metro, STATE AS state, 'SNOWFLAKE-CSV-ZIP-METRO' AS sourceId FROM source_zip_metro_raw WHERE (? IS NULL OR LPAD(REGEXP_REPLACE(CUSTOMER_ADDRESS_ZIP, '[^0-9]', '', 'g'), 5, '0') = ?) LIMIT 1000"; values = [parsed.zip ?? null, parsed.zip ?? null]; break;
    case "clinic_market_evidence": sql = "SELECT cbsaCode, cbsaName, clinicCount, clinicDensityPer10000Households, clinicDensityStatus, status, source.sourceId AS sourceId FROM clinic_market_summary WHERE (? IS NULL OR cbsaCode = ?) LIMIT 1000"; values = [parsed.cbsaCode ?? null, parsed.cbsaCode ?? null]; break;
    case "appointment_context": sql = "SELECT geography, reportingMonth, appointmentType, appointmentState, reason, appointmentCount, source.sourceId AS sourceId FROM appointment_context WHERE (? IS NULL OR geography = ?) LIMIT 5000"; values = [parsed.geography ?? null, parsed.geography ?? null]; break;
    case "retention_context": sql = "SELECT reportingYear, reportingPeriod, reportingWeek, weekStartDate, aggregationLevel, businessChannel, totalCustomers, source.sourceId AS sourceId FROM retention_baseline WHERE (? IS NULL OR reportingYear = ?) LIMIT 2000"; values = [parsed.reportingYear ?? null, parsed.reportingYear ?? null]; break;
    case "google_ads_matched_location_context": throw new Error("Google Ads matched-location evidence is registered in the canonical Parquet snapshot but is not connected to this legacy snapshot query service. Use the canonical execution service after it is implemented.");
    case "google_ads_market_aggregates": throw new Error("Google Ads market aggregation is blocked because the registered exports do not contain stable geography IDs.");
    case "source_quality_summary": sql = "SELECT table_name AS tableName, sensitivity, allowed_use AS allowedUse, expected_row_count AS expectedRowCount, actual_row_count AS actualRowCount, duplicate_key_count AS duplicateKeyCount, quality_warning_count AS qualityWarningCount, date_min AS dateMin, date_max AS dateMax FROM snapshot_table_registry WHERE snapshot_version = ? UNION ALL SELECT table_name AS tableName, sensitivity, allowed_use AS allowedUse, row_count AS expectedRowCount, row_count AS actualRowCount, 0 AS duplicateKeyCount, 0 AS qualityWarningCount, NULL AS dateMin, NULL AS dateMax FROM source_registry WHERE snapshot_version = ?"; values = [parsed.snapshotVersion, parsed.snapshotVersion]; break;
  }
  let reader;
  try { reader = await connection.runAndReadAll(sql, values); } catch (error) { await closeDuckDb(handle); throw new Error(`The requested dataset is not loaded or its registered query failed: ${error instanceof Error ? error.message : "unknown error"}`); }
  const rows = reader.getRowObjectsJson(); await closeDuckDb(handle);
  return { query: parsed.query, rows, snapshotVersion: parsed.snapshotVersion, queryVersion: SNAPSHOT_QUERY_VERSION, evidenceBoundary: "Registered aggregate evidence only. Raw CSV rows, arbitrary SQL, and fields outside the query contract are excluded from browser and AI output.", allowedUse: "approved_internal_decision_support", qualityWarnings: readiness.knownIssues, unmatchedCounts: readiness.unmatchedGeographyCounts, sourceDatasetsLoaded: readiness.sourceDatasetsLoaded };
}
