import { normalizationSourceDefinitionSchema, type NormalizationSourceDefinition } from "./contracts.ts";

function source(definition: NormalizationSourceDefinition): NormalizationSourceDefinition {
  return normalizationSourceDefinitionSchema.parse(definition);
}

export const normalizationSourceCatalog = [
  source({ datasetId: "market_context", sourceFamily: "general_regional", relativePath: "General Regional/cbsa_market_attractiveness_2026-07-31-1246 (1).csv", sourceId: "SNOWFLAKE-CSV-MARKET-CONTEXT", grain: "one reported CBSA market x reporting date", requiredColumns: ["CBSA_CODE", "CBSA_NAME", "REPORTING_DATE", "ACTIVE_CUSTOMER_COUNT", "ACTIVE_CUSTOMER_YOY_GROWTH"], geographyStrategy: "cbsa_code_or_label", geographyFields: { cbsaCode: "CBSA_CODE", cbsaLabel: "CBSA_NAME" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "cbsa_population", sourceFamily: "general_regional", relativePath: "General Regional/cbsa_population_estimates.csv", sourceId: "SNOWFLAKE-CSV-CBSA-POPULATION", grain: "one CBSA x population estimate", requiredColumns: ["CBSA", "LSAD", "POP_ESTIMATE"], geographyStrategy: "cbsa_code", geographyFields: { cbsaCode: "CBSA" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "zip_market", sourceFamily: "general_regional", relativePath: "General Regional/zip_code_to_cbsa_csa_statistical_area_mapping.csv", sourceId: "SNOWFLAKE-CSV-ZIP-MARKET", grain: "one ZIP x reported CBSA mapping", requiredColumns: ["ZIP_CODE", "CBSA_TITLE", "METRO_MICRO_STATISTICAL_AREA"], geographyStrategy: "zip_to_cbsa", geographyFields: { zip: "ZIP_CODE", cbsaLabel: "CBSA_TITLE" }, sensitivity: "internal", allowedUse: "local_demo_geography_bridge", browserExposure: "aggregate_only" }),
  source({ datasetId: "zip_metro", sourceFamily: "general_regional", relativePath: "General Regional/customer_zip_to_metro_state_mapping.csv", sourceId: "SNOWFLAKE-CSV-ZIP-METRO", grain: "one ZIP x metro x state", requiredColumns: ["CUSTOMER_ADDRESS_ZIP", "METRO", "STATE"], geographyStrategy: "zip_to_cbsa", geographyFields: { zip: "CUSTOMER_ADDRESS_ZIP", cbsaLabel: "METRO", state: "STATE" }, sensitivity: "internal", allowedUse: "local_demo_geography_bridge", browserExposure: "aggregate_only" }),
  source({ datasetId: "zip_context", sourceFamily: "general_regional", relativePath: "General Regional/zcta5_household_income_and_family_estimates_2026-08-10.csv", sourceId: "SNOWFLAKE-CSV-ZIP-CONTEXT", grain: "one ZCTA5 x household context", requiredColumns: ["GEO_ZIPCODE", "ESTIMATED_HOUSEHOLDS", "ESTIMATED_MEDIAN_HOUSEHOLD_INCOME"], geographyStrategy: "zip_to_cbsa", geographyFields: { zip: "GEO_ZIPCODE" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "regional_demand", sourceFamily: "general_regional", relativePath: "General Regional/annual_net_sales_by_customer_zip.csv", sourceId: "SNOWFLAKE-CSV-REGIONAL-DEMAND", grain: "one customer-address ZIP x year", requiredColumns: ["YEAR", "CUSTOMER_ADDRESS_ZIP", "NET_SALES_EXCLUDING_REFUNDS", "NET_SALES"], geographyStrategy: "zip_to_cbsa", geographyFields: { zip: "CUSTOMER_ADDRESS_ZIP" }, sensitivity: "internal", allowedUse: "local_demo_cbsa_aggregate_only", browserExposure: "aggregate_only" }),
  source({ datasetId: "clinic_profile", sourceFamily: "clinic", relativePath: "Clinic/clinic_market_profile_ownership_demographics.csv", sourceId: "SNOWFLAKE-CSV-CLINIC-PROFILE", grain: "one clinic profile row", requiredColumns: ["CLINIC_ID", "ZIP_CODE", "CBSA_NAME", "CLINIC_STATE", "TOTAL_ORDERS", "TOTAL_VETS_CAPPED"], geographyStrategy: "zip_then_cbsa_label", geographyFields: { clinicId: "CLINIC_ID", zip: "ZIP_CODE", cbsaLabel: "CBSA_NAME", state: "CLINIC_STATE" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "clinic_activity", sourceFamily: "clinic", relativePath: "Clinic/clinic_level_pre_post_ph_orders_prescriptions_sales.csv", sourceId: "SNOWFLAKE-CSV-CLINIC-ACTIVITY", grain: "one clinic x timeframe activity row", requiredColumns: ["CLINIC_ID", "ZIP_CODE", "TIMEFRAME", "TOTAL_CUSTOMER", "TOTAL_ORDERS", "NET_SALES"], geographyStrategy: "clinic_identity_then_zip", geographyFields: { clinicId: "CLINIC_ID", zip: "ZIP_CODE" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "appointments", sourceFamily: "clinic", relativePath: "Clinic/monthly_appointment_counts_by_geography_type_state_reason.csv", sourceId: "SNOWFLAKE-CSV-APPOINTMENTS", grain: "one state x month x appointment dimensions", requiredColumns: ["GEOGRAPHY", "REPORTING_MONTH", "APPOINTMENT_TYPE", "APPOINTMENT_STATE", "REASON", "APPOINTMENT_COUNT"], geographyStrategy: "state", geographyFields: { state: "GEOGRAPHY" }, sensitivity: "internal", allowedUse: "local_demo_aggregate_decision_support", browserExposure: "aggregate_only" }),
  source({ datasetId: "retention", sourceFamily: "clinic", relativePath: "Clinic/weekly_customer_lifecycle_retention_metrics_by_channel.csv", sourceId: "SNOWFLAKE-CSV-RETENTION", grain: "one week x aggregation level x business channel", requiredColumns: ["WEEK_START_DATE", "AGGREGATION_LEVEL", "BUSINESS_CHANNEL", "TOTAL_CUSTOMERS"], geographyStrategy: "national", geographyFields: {}, sensitivity: "internal", allowedUse: "local_demo_national_context_only", browserExposure: "aggregate_only" }),
  source({ datasetId: "google_ads_search_shopping", sourceFamily: "google_ads", relativePath: "Google Ads/Chewy Seach_Shopping.csv", sourceId: "GOOGLE-ADS-MATCHED-CHEWY-SEACH-SHOPPING", grain: "one matched-location label x report scope x observation window", requiredColumns: ["Matched location", "Clicks", "Impr.", "Cost", "Conversions"], geographyStrategy: "matched_location_label", geographyFields: { matchedLocation: "Matched location" }, sensitivity: "internal", allowedUse: "local_demo_inferred_regional_context", browserExposure: "aggregate_only" }),
  source({ datasetId: "google_ads_vet_clinic_search", sourceFamily: "google_ads", relativePath: "Google Ads/Chewy Vet Clinic Seach.csv", sourceId: "GOOGLE-ADS-MATCHED-CHEWY-VET-CLINIC-SEACH", grain: "one matched-location label x report scope x observation window", requiredColumns: ["Matched location", "Clicks", "Impr.", "Cost", "Conversions"], geographyStrategy: "matched_location_label", geographyFields: { matchedLocation: "Matched location" }, sensitivity: "internal", allowedUse: "local_demo_inferred_regional_context", browserExposure: "aggregate_only" }),
] as const;

export type NormalizationDatasetId = typeof normalizationSourceCatalog[number]["datasetId"];

export const normalizationSourceById = new Map(normalizationSourceCatalog.map((item) => [item.datasetId, item]));

export function assertNoSeoSources() {
  if (normalizationSourceCatalog.some((item) => item.relativePath.startsWith("SEO Keywords/"))) {
    throw new Error("National SEO files must remain outside the regional normalization catalog.");
  }
}
