import snapshot from "../../data/approved/adaptive-discovery/current.json" with { type: "json" };

export const ADAPTIVE_DECISION_INSIGHTS_VERSION = snapshot.version;

type SnapshotFinding = {
  id: string;
  type: string;
  question: string;
  hypothesis: string;
  evidenceStatus: string;
  geography: { type: string; label: string };
  period: string;
  confidence: { level: string; reason: string };
  metrics: Array<{ id: string; label: string; value: number; unit: string; benchmark?: string | number; calculation: string }>;
  evidence: string[];
  implication: string;
  proposedAction: string;
  decisionBoundary: string;
  limits: string[];
  sourceIds: string[];
  sourceFiles: string[];
};

export type AdaptiveDecisionFinding = SnapshotFinding & {
  departments: Array<"marketing" | "pricing" | "cvc">;
  findingKind: "opportunity" | "contradiction" | "quality" | "price_test" | "competitive_risk" | "cross_functional";
};

function withScope(
  finding: SnapshotFinding,
  departments: AdaptiveDecisionFinding["departments"],
  findingKind: AdaptiveDecisionFinding["findingKind"],
): AdaptiveDecisionFinding {
  return { ...finding, departments, findingKind };
}

/**
 * Returns hypotheses produced from the evidence itself. These are generated by
 * reusable cohort, contradiction, decomposition, quality, and SKU-gap
 * operators rather than by the starter-question registry.
 */
export function getAdaptiveDecisionFindings(): AdaptiveDecisionFinding[] {
  const findings: AdaptiveDecisionFinding[] = [
    ...snapshot.discoveries.matchedDmaCrossAccount.jointOpportunities.map((item) => withScope(item as SnapshotFinding, ["marketing"], "opportunity")),
    ...snapshot.discoveries.matchedDmaCrossAccount.contradictions.map((item) => withScope(item as SnapshotFinding, ["marketing"], "contradiction")),
    ...snapshot.discoveries.cvcChannelMix.questions.map((item) => withScope(item as SnapshotFinding, ["cvc", "marketing"], "cross_functional")),
    ...snapshot.discoveries.dogFoodPricing.raiseCandidates.slice(0, 5).map((item) => withScope(item as SnapshotFinding, ["pricing"], "price_test")),
    ...snapshot.discoveries.dogFoodPricing.riskCandidates.slice(0, 5).map((item) => withScope(item as SnapshotFinding, ["pricing"], "competitive_risk")),
    ...(snapshot.discoveries.nationalDogFoodContext?.hypotheses ?? []).map((item) => withScope(item as SnapshotFinding, ["marketing", "pricing"], "cross_functional")),
  ];
  return findings;
}

export function getAdaptiveDiscoveryAudit() {
  const findings = getAdaptiveDecisionFindings();
  return {
    version: snapshot.version,
    generatedAt: snapshot.generatedAt,
    method: "data_generated_decision_hypotheses" as const,
    sourceCount: snapshot.sources.length,
    generatedCount: findings.length,
    testedCount: findings.filter((finding) => finding.evidenceStatus === "Derived").length,
    findings,
  };
}
