import type { StructuredEvidenceResult } from "./types";

export const SYNTHETIC_EVIDENCE_RESULT: StructuredEvidenceResult = {
  evaluationId: "SYN-EVAL-101",
  candidateLabel: "Synthetic River District",
  evaluatedAt: "2026-07-24",
  sources: [
    {
      sourceId: "SYN-SRC-101",
      sourceLabel: "Synthetic market aggregate",
      evidenceStatus: "Hypothesis",
      observedAt: "2026-06-30",
      extractedAt: "2026-07-01",
      geography: "15-minute drive-time area",
      aggregation: "Synthetic index",
      qualityStatus: "accepted",
      sensitivity: "public",
    },
    {
      sourceId: "SYN-SRC-102",
      sourceLabel: "Synthetic competitor inventory",
      evidenceStatus: "Reported",
      observedAt: "2025-12-31",
      extractedAt: "2026-07-01",
      geography: "5-mile radius",
      aggregation: "Count",
      qualityStatus: "warning",
      sensitivity: "internal",
      freshnessWarning: "Observation is older than the demonstration threshold.",
    },
    {
      sourceId: "SYN-SRC-103",
      sourceLabel: "Synthetic qualitative field note",
      evidenceStatus: "Reported",
      observedAt: "2026-06-18",
      extractedAt: "2026-06-19",
      geography: "Local market",
      aggregation: "Non-scored observation",
      qualityStatus: "accepted",
      sensitivity: "internal",
    },
    {
      sourceId: "SYN-SRC-RESTRICTED",
      sourceLabel: "This restricted label must not render",
      evidenceStatus: "Confirmed",
      observedAt: "2026-07-01",
      extractedAt: "2026-07-02",
      geography: "Restricted geography",
      aggregation: "Restricted aggregation",
      qualityStatus: "accepted",
      sensitivity: "restricted",
    },
  ],
  metrics: [
    {
      metricId: "demand_index",
      metricLabel: "Customer demand index",
      sourceIds: ["SYN-SRC-101"],
      unit: "index points",
      rawValue: 74,
      normalizedValue: 74,
      weight: 30,
      contribution: 22.2,
      scoringRole: "weighted",
      disposition: "scored",
    },
    {
      metricId: "competitor_count",
      metricLabel: "Competitor count",
      sourceIds: ["SYN-SRC-102"],
      unit: "locations",
      rawValue: 6,
      normalizedValue: 52,
      weight: 20,
      contribution: 10.4,
      scoringRole: "weighted",
      disposition: "scored",
      freshnessWarning: "The source observation is stale.",
    },
    {
      metricId: "staffing_feasibility",
      metricLabel: "Staffing feasibility",
      sourceIds: ["SYN-SRC-UNKNOWN"],
      rawValue: null,
      scoringRole: "constraint",
      disposition: "missing",
      statusReason: "No approved synthetic observation is available.",
    },
    {
      metricId: "foot_traffic_proxy",
      metricLabel: "Foot-traffic proxy",
      sourceIds: ["SYN-SRC-RESTRICTED"],
      unit: "index points",
      rawValue: null,
      scoringRole: "weighted",
      disposition: "rejected",
      statusReason: "Restricted input was not admitted to the prototype.",
    },
    {
      metricId: "local_market_note",
      metricLabel: "Local-market note",
      sourceIds: ["SYN-SRC-103"],
      scoringRole: "qualitative",
      disposition: "unscored",
      statusReason: "Qualitative evidence is not converted into a score.",
    },
  ],
  qualitativeEvidence: [
    {
      evidenceId: "SYN-QUAL-101",
      summary:
        "Synthetic observation retained for review and excluded from numeric scoring.",
      sourceIds: ["SYN-SRC-103"],
      evidenceStatus: "Reported",
      qualityStatus: "accepted",
      sensitivity: "internal",
      observedAt: "2026-06-18",
      geography: "Local market",
    },
  ],
  missingInformation: [
    {
      itemId: "staffing-input",
      label: "Approved staffing-feasibility input",
      status: "missing",
      detail: "The formula, owner, and approved source remain unknown.",
      sourceId: "SYN-SRC-UNKNOWN",
    },
    {
      itemId: "candidate-source",
      label: "Approved candidate pipeline source",
      status: "unavailable",
      detail: "The prototype does not connect to an internal candidate system.",
    },
  ],
  warnings: [
    {
      warningId: "stale-competitor-source",
      severity: "warning",
      title: "Competitor observation is stale",
      detail: "Review the observation date before interpreting the contribution.",
      metricIds: ["competitor_count"],
      sourceIds: ["SYN-SRC-102"],
    },
    {
      warningId: "restricted-input-rejected",
      severity: "info",
      title: "Restricted input was rejected",
      detail: "Restricted values are not displayed or scored.",
      metricIds: ["foot_traffic_proxy"],
      sensitivity: "restricted",
    },
  ],
};
